### ISSUE TITLE
🐞 Bug: 9.4.1.2 link group: Nav-Element ist irreführend

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5669]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Die Gruppen von Links befinden sich in einem `<nav>`-Element. Das KANN richtig sein, wenn es sich um eine Liste zur Navigation handelt. Als Beispiel ist das aber irreführend, da nicht jede Link-Liste ein Navigationsbereich sein sollte.

## Reproduktion
Komponente: link-group basic/horizontal (https://public-ui.github.io/v2/sample-react/#/link-group/basic)
Version: v2.0.0-rc.11

## Erwartetes Verhalten
Im Beispiel sollten die Link-Gruppen ohne nav-Elementumgesetzt werden. Dass eine Link-Liste die der Navigation dient als nav-Region umgesetzt werden kann sollte im Text bzw. als Option vorhanden sein.

**Comment by laske185** [comment]
Welche Berechtigung hat diese Komponente?
Ohne Nav-Element hat sie keine Daseinsberechtigung.
Welcher Anwendungsfall wird hiermit abgebildet?

**Comment by fohi17** [comment]
Beschluss: nav sollte für das Beispiel entfernt werden. Die Liste benötigt auch kein Label. Dass Listen in ihrem Verwendungskontext beschriftet bzw. zuordenbar sind muss von den Nutzern der Komponente sichergestellt werden bspw. durch eine Überschrift. Der Hinweis auf Beschriftung und die Möglichkeit, dass es eine Nav-Region sein KANN wird in die Doku aufgenommen.

**Comment by deleonio** [comment]
**TODO:**

A:
Code: https://github.com/public-ui/kolibri/blob/develop/packages/components/src/components/link-group/component.tsx
- [x] `nav`-Tag entfernen
- [x] CSS-Styling auf `ol` und `ul` verschieben
- `_label` ist dann nicht mehr required
  - https://github.com/public-ui/kolibri/blob/c2ef81184766632910d98fb0264b602e014aa70b/packages/schema/src/components/link-group.ts#L22C6-L22C19
  - [x] `@Prop() public _label?: LabelPropType;`
  - [x] ⚠️ `@public-ui/schema` - LinkGroupProps anpassen. `_label` aus `LinkGroupStates` entfernen.

B:
- [x] Dokumentation
  - [x] Hinweis in die [README](https://github.com/public-ui/kolibri/blob/develop/packages/components/src/components/link-group/readme.md) einfügen, dass diese Komponente für Version 3 `deprecated` ist, weil sie keinen nennenswerten Beitrag zur Barrierefreiheit beiträgt.
  - [x] Hinweis darauf, dass ein `nav`-Tag um die Liste eingefügt wird, der nicht zwingend aus Sicht der Barrierefreiheit erforderlich ist.
- [x] Umbauen tun wir an der Komponente nichts - markieren diese jedoch als `@deprecated` (`JSDoc`)
- [x] Neues Ticket anlegen, für Version 3 (Label `for v3`)
