### ISSUE TITLE
🐞 Bug: 9.4.1.2 button-group: Gruppierung ist nicht erkennbar

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5707]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Die Gruppierung heißt zwar "button-group" eine Gruppierung (abgesehen von der visuellen Anordnung) ist jedoch nicht erkennbar. Mit dem Screenreader ist keine Zusammengehörigkeit der Buttons erkennbar. 

## Reproduktion
Komponente: button-group basic (https://public-ui.github.io/v2/sample-react/#/button-group/basic)
Version: v2.0.0-rc.12

## Erwartetes Verhalten
Die Zusammengehörigkeit der Buttons sollte auch programmatisch erkennbar sein. Möglichkeiten wären eine Liste oder Toolbar.

**Comment by deleonio** [comment]
Der beschriebene Mangel wird mit der Umsetzung der Toolbar-Komponente behoben. Die Komponente Button-Group wird damit abgelöst und im nächsten Major-Release entfernt.

- https://github.com/public-ui/kolibri/issues/5728

**Comment by deleonio** [comment]
**TODO:**
- [ ] Dokumentation
  - [ ] Hinweis in die README einfügen, dass diese Komponente für Version 3 `deprecated` ist, weil sie keinen nennenswerten Beitrag zur Barrierefreiheit beiträgt.
- [ ] Umbauen tun wir an der Komponente nichts - markieren diese jedoch als `@deprecated` ([`JSDoc`](https://jsdoc.app/tags-deprecated))
- [ ] Neues Ticket anlegen, für Version 3 (Label `for v3`)
