### ISSUE TITLE
🛠️ Todo: CSS: Tag-Selektoren umstellen

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6054]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Beschreibung

In Vorbereitung für #6019 müssen wir Verwendungen von Tagnames der KoliBri-Komponenten im CSS entfernen.

Selektoren wie z.B. `kol-avatar {}` oder `kol-span {}` müssen also angepasst werden, reguläre HTML-Tag-Selektoren wie `div {}` oder `table {}` dürfen erst einmal bleiben.

# Todo

- [ ] Alle Komponenten bekommen ihren Tagname als Klasse auf dem äußeren Element der Render-Funktion. 

Bei Avatar würde die Änderungen z.B. so aussehen:

Shadow:
```diff
- return (
-     <Host>
-         <kol-avatar-wc _src={this._src} _label={this._label}></kol-avatar-wc>
+ return (
+     <Host>
+         <kol-avatar-wc _src={this._src} _label={this._label} class="kol-avatar"></kol-avatar-wc>
```

Component:
```diff
-return (
-    <Host>
-        <div aria-label={translate('kol-avatar-alt', { placeholders: { name: this.state._label } })} class="container" role="img">
+return (
+    <Host>
+        <div aria-label={translate('kol-avatar-alt', { placeholders: { name: this.state._label } })} class="kol-avatar-wc container" 
```

- [ ] Alle Verwendungen von Tagname-Selektoren im CSS werden auf Klassen-Selektoren umgeschrieben.
  - [ ] Basis-Styles
  - [ ] Component-Styles
  - [ ] Themes

Beispiel:

```diff
- kol-input:not(.checkbox, .radio) .input:focus-within,
+ .kol-input:not(.checkbox, .radio) .input:focus-within {
```

Tipp: Global in `*.scss,.css,.ts` nach `kol-` suchen.

**Comment by sdvg** [comment]
@anicyne Ich habe hier mit Martin noch mal folgende Änderung besprochen:
Wir fügen die neuen Klassennamen doch am `<Host>`, nicht am root-Element der Komponenten ein.

Das erleichtert die Umstellung insgesamt, da die angepassten CSS-Selektoren das selbe Element wie zuvor referenzieren können. `kol-span {}` kann also einfach zu `.kol-span {}` geändert werden, und das selbe Element wird selektiert.

Checkliste:
- [x] Jede Komponente (component.tsx und shadow.tsx) hat ein `<Host>`-Element.
- [x] Jedes `<Host>`-Element hat ein `class`-Attribut, dass dem `tag` der `@Component`-Annotation entspricht.
-- Weitere Änderungen an den `class`-Attributen sollten nicht notwendig sein und müssen ggf. rückgängig gemacht werden.
- [x] Das Styling bleibt unverändert. Hier müssen ggf. auftretende Probleme durch die veränderte Spezifität (Tag vs. Class-Selektor) korrigiert werden.
