### ISSUE TITLE
🛠️ Todo: Component-Naming bzgl. `component.tsx` und `shadow.tsx` aufräumen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6105]
# Akzeptanzkriterien

- [x] `shadow.tsx` alle Komponenten bei denen `shadow: true` ist
- [x] `component.tsx` alle Komponenten bei denen `shadow: false` ist
- [x] Klassen-Name ohne `Wc` bei allen Komponenten wo `shadow: true` ist
- [x] Klassen-Name mit `Wc` bei allen Komponenten wo `shadow: false` ist
- [x] CSS-Klassen bleiben unberührt
