### ISSUE TITLE
🛠️ Todo: Beschreibung der Test-Objekte optimieren

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6171]
Die Beschreibungen der Test-Objekte (Beispiele) ist noch nicht ganz zutreffend bzw. konkret genug.

In der Sample-App bitte die Beschreibungen verbessern.

- [x] zuerst `v2` verbessern
- [x] danach für `v1` übernehmen
- [x] Beschreibungen auf Englisch übersetzen.
- [x] Die UI komplett auf Englisch übersetzen

**Comment by sdvg** [comment]
Reopen für `v1`.

**Comment by sdvg** [comment]
PR lässt sich nicht verlinken: https://github.com/public-ui/kolibri/pull/6666
