### ISSUE TITLE
🛠️ Todo: Formular-Handling Demo bei Terminauswahl verbessern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6183]
Aktuell sind keine Termine verfügbar. Wählt man einen Termin mittels Tastatur aus, kann man trotzdem auf Weiter drücken. Kehrt man zurück, wird die Uhrzeit nicht wieder eingetragen.

Mit der Maus kann kein Termin ausgewählt werden. Beim Klick auf Weiter wird auch ein Fehler angezeigt.

Todos:

- [x] Deaktivieren des Weiter-Schalters generell nicht machen / ausbauen
- [x] Einige valide Termine wieder auswählbar machen (aktuell alle nicht wählbar)
- [x] Fokus auf Fehlerliste funktioniert beim initialen Einblenden nicht (hier muss sicher ein Render-Cycle abgewartet werden, `setTimeout`)

**Comment by chrisalat** [comment]
`Einige valide Termine wieder auswählbar machen` tritt nur in V2 auf
