### ISSUE TITLE
🛠️ Todo: Git hook `prepare-commit-msg`

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6201]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

## Problem

Commit-Messages sind zur Zeit nicht einfach einem Ticket zuzuordnen.

## Lösung

Jede Commit Message wird automatisch mit der Nummer des Tickets geprefixed. Zudem wird schon ab dem ersten Commit validiert, dass der Branch die Ticket-Nummer enthält.

## Akzeptanzkriterien

- [x] Ein `prepare-commit-msg` Git-Hook wird wird für jede:n Benutzer:in automatisch in der Entwicklungsumgebung installiert.
- [x] Beginnt ein Branch-Name nicht mit `\d+[-_]`, wird der Commit automatisch abgelehnt.
- [x] Bei einem korrekten Branch-Namen wird einer Commit-Message automatisch die Ticket-Nummer vorangestellt.
- [x] Funktionsfähigkeit auf Windows (Git Bash?) und Unix Systemen

Beispiel:

```
user in ~/Projects/kolibri on 5484-fix-dialog-stacking [!?$]
$ git commit -am 'Fix things'
```

Erzeugt die Commit message: `#5484 Fix things`

## Referenzen

Hier ein Implementierungsbeispiel, das nur leicht angepasst werden müsste: https://medium.com/@adrian.garcia.estaun/add-the-ticket-id-to-your-commit-messages-automatically-2debfa0fbe9d
Die Installation des Git-Hooks kann [Husky](https://github.com/typicode/husky) für uns übernehmen.
