### ISSUE TITLE
🛹 Feature: `Tabs` new `_behavior` property for alternative control

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6249]
**PoC**: Je nachdem, ob die Komponente wartbar bleibt oder nicht, werden wir die Änderung übernehmen.

Es ist alternativ möglich, mit den Pfeiltasten nur den Fokus zu verschieben und das Wechseln der Tabs durch Enter erst auszuführen. 

- [ ] https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/
- [x] https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/ (since `v1`)

### Todo

- [ ] Neue Property `_behavior` (Typ: `TabBehaviorType`) anlegen, mit den möglichen Werten `select-automatic` und `select-manual`
- [ ] Je nach Behavior wird das fokussierte Tab sofort geöffnet oder erst nach Drücken auf Enter
