### ISSUE TITLE
🛹 Feature: Shortkey ermöglichen bei Tooltips

### ISSUE THREAD

**Issue by gkollotzek** [public-ui/kolibri#6251]
Wie im heutigen gemeinsamen Termin besprochen die Feature Anfrage für Shortkeys:

- Sieht optisch wie ein Access-Key aus, z.B. 
<img width="209" alt="image" src="https://github.com/public-ui/kolibri/assets/138562317/aae4065f-91d0-4ffc-81d5-4cb2a3f2b2a6">

- aber es soll kein accesskey verwendet werden 
(Anwendungsbeispiel: Zuletzt fokussierte Tabellenzeile soll durch Shortkey angezeigt ("A")/ bearbeitet ("B") /gedruckt ("D") werden)
- Für Screenreader muss versteckter Text angezeigt werden, dass es sich um einen Shortkey handelt
- Das Event-Handling wird von der Anwendung übernommen (nicht Teil von KoliBri)

## To-do

- Tooltip und Span erweitern
  - [x] Umbenennung der Property "_accessKey" in "_badgeText"
  - [x] Badge bleibt aria-hidden
- Link, Button, Inputs, Select, Textarea (alle die `_accessKey` umgesetzt haben)
  - [x] Gleichzeitige Verwendung `_accessKey` und `_shortKey` erzeugt Fehler
  - [x] `_shortKey` setzt `BadgeKey` am Tooltip
  - [x] Accessability-Text wird erweitert, analog wie `_accessKey` von Screenreadern vorgelesen wird
- [x] Samples bei den betroffenen Komponenten anlegen.

## Abgrenzung:

OS-Spezifische Steuertasten (Strg, Alt, Win, Cmd) werdem **nicht** von KoliBri gesetzt. Diese müssen von der Anwendung, z. B. als Font-Icon, korrekt übergeben werden.

Dies muss in der Readme dokumentiert werden.

**Comment by laske185** [comment]
Wenn shortkey gesetzt ist, dann muss auch der listener ein Pflichtfeld sein.
