### ISSUE TITLE
🛠️ Todo: Erweiterung Dokumentation Tabelle

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6299]
## Beschreibung

Folgende Punkte sollten ergänzt werden:

- [ ] Dokumentation am Quellcode
- [ ] Render function: Beschreibung aller Parameter.
- [ ] Multi Sort: Präzise Beschreibung der Funktionalität, Sicherstellen eines Beispiels in der React App.
