### ISSUE TITLE
🛠️ Todo: Deprecated Table Features entfernen (für V3)

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6303]
# Todo

- [ ] KolTable entfernt (wurde ersetzt durch KolTableStateful)
- [ ] `@deprecated`-annotierte Features in KolTableStateful entfernt
- [ ] `@deprecated`-annotierte Features in KolTableStatless entfernt

**Comment by sdvg** [comment]
Wurde erledigt in [#7015](https://github.com/public-ui/kolibri/issues/7015)
