### ISSUE TITLE
🛠️ Todo: Migrations-Tool: `KolTable` zu `KolTableStateful` umschreiben

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6325]
# Todo

Nur der Komponent-Name ändert sich, die API ist unverändert geblieben.

- [ ] Neuen Common-Taks für TagName-Rename erstellen (like https://github.com/public-ui/kolibri/blob/develop/packages/tools/kolibri-cli/src/migrate/runner/tasks/common/GenericRenamePropertyTask.ts)
- [ ] Neue Common-Klasse `RenameTagNameTask` in `common` anlegen
  - [ ] Identifier: `rename-tag-name-<from>-to-<to>`
  - [ ] Paramenter `oldTagName`, `newTagName`
  - [ ] Range: `>=2.1.7 <3`
  - [ ] depTasks: keine
  - [ ] `options` ??? 
- [ ] Es wird eine neue Klasse für die Code-Modifikation benötig: `GenericRenameTagNameTask`
