### ISSUE TITLE
🛠️ Todo: Projektkonfiguration verbessern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6351]
PNPM v9 needs reconfiguration of our mono repository.

- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines
- https://pnpm.io/workspaces

### Todos

- [x] `engines` in der `package.json` festlegen
  - ~~`node: ^20`~~ (nicht erforderlich, da keine Auswirkung)
  - ~~`npm: ^10`~~ (nicht erforderlich, da keine Auswirkung)
  - `pnpm: ^8` (erforderlich)
- [x] ~~nvmrc~~ (NVM funktioniert nicht unter Windows)
- [x] `packageManager: pnpm@^8` in der `package.json` festlegen

**Comment by sdvg** [comment]
Der Package Manager kann ebenfalls definiert werden: https://nodejs.org/dist/latest-v16.x/docs/api/all.html#all_packages_packagemanager

Außerdem nice to have: [nvm rc](https://janikvonrotz.ch/2022/03/17/create-and-use-nvm-rc-file/)

**Comment by deleonio** [comment]
https://stackoverflow.com/questions/71747609/how-to-specify-packagemanager-in-package-json

`"packageManager": "^pnpm@6.32.4"`

**Comment by laske185** [comment]
nvm ist nur für Linux und MacOS.
