### ISSUE TITLE
🛠️ Todo: `@public-ui/schema` in `components` umziehen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6352]
Die Typen werden in der IDE nur auf Pakete aufgelöst, die direkte Dependencies aus der eigenen package.json sind. Somit funktioniert der Ansatz die Typen über `components` zu leiten leider nicht.

Da wir die Schema's aktuell für keine 2. Lib brauchen, sollten wir diese wieder in components verorten. Dort sollten sie für die Zukunft in einem eigenen Ordner `schema` zusammen bleiben (wie ein Modul).

### Todos 

- [ ] Neuer Ordner in componts: `schema` anlegen
- [ ] Komplette src-Ordner aus schema dort hin verschieben
- [ ] Imports anpassen
- [ ] `schema` Paket entfernen
