### ISSUE TITLE
🛠️ Todo: Angular-Adapter auf v18 upgraden / alte Adapter entfernen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6501]
- [x] ein neues package hinzufügen für Angular 18 (nur v2)
- [x] alte nicht mehr von Angular gemaintainte Pakete bei uns auch entfernen
- [x] https://github.com/public-ui/lab-micro-frontends auf v18 aktualisieren (nur v2)

**Comment by sdvg** [comment]
Micro Frontends zu aktualisieren ist noch offen. Hier gibt es (mutmaßlich) Probleme mit `pnpm link`, daher würde ich um Zeit zu sparen das Release vom Angular 18 Adapter abwarten.
Das Angular-Sample innerhalb des Monorepo funktioniert mit dem neuen Adapter ✅

**Comment by sdvg** [comment]
Ticket noch mal geöffnet, um nach dem Release ebenfalls die Micro-Frontends zu aktualisieren.
