### ISSUE TITLE
🛠️ Todo: E2E-Tests: Setup mit Stencil Dev Server und setContent

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6512]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Todo

Aufbauend auf: https://github.com/public-ui/kolibri/pull/6471

- [x] "Finales" Setup ohne React Sample App, z.B. mit dem Stencil Dev Server konfigurieren
- [x] Test mit dem [`setContent`-Pattern](https://stenciljs.com/docs/testing/playwright/e2e-testing#pagesetcontent) ermöglichen
- [x] Exemplarisch Tests für 1-2 Komponenten erstellen
- [x] Tests in CI-Pipeline integrieren
