### ISSUE TITLE
🛠️ Todo: Beispielhafte Playwright-E2E-Tests in React Sample App integrieren

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6513]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

Grundlage als Konfigurationsbeispiel: https://github.com/public-ui/kolibri/pull/6471

- [x] Die Tests werden Teil des React Sample App Pakets
- [x] Nicht alle Komponenten müssen getestet werden, Fokus liegt auf wenigen guten Beispielen
- [x] Tests z.B. für die Szenarios umsetzen

**Comment by laske185** [comment]
Abhängig von https://github.com/public-ui/kolibri/issues/6512
