### ISSUE TITLE
Investigation/Todo: npm provenance statements

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6561]
Dieses Ticket ist von folgendem Ticket abhängig: https://github.com/public-ui/kolibri/issues/6566

Um die Sicherheit und das Vertrauen in KoliBri Pakate auf npm zu verbessern, können wir [npm provenance statements](https://docs.npmjs.com/generating-provenance-statements) generieren.

Beispiel, wie das aussieht: https://www.npmjs.com/package/@stencil/core
<img width="839" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/af139782-bb64-4ce6-bcaf-8c12bae786a2">

### Akzeptanzkriteren

- [x] Wir haben einen Überblick darüber, was Provenance Statements für uns bedeuten. Mit Vorteilen und mgl. Nachteilen und Blockern.
- [x] Wir wissen, wie wir das Generieren von Provenance Statements in unsere Workflows integrieren können.
- [x] (Optional, idealerweise) Das Generieren von Provenance Statements ist in unsere Workflows fertig integriert.
  - Alternativ: Issue angelegt, wo die notwendigen Schritte beschrieben werden.

**Comment by deleonio** [comment]
Kannst Du bitte auch `v1` machen.
