### ISSUE TITLE
Todo: React Sample App Type Issues beheben

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6563]
Die React Sample App hat recht viele Type Issues angesammelt, die bei der Entwicklung teilweise stören und auch kein ideales Beispiel abgeben.

### Akzeptanzkriterien

- [x] Type Issues wurden behoben
- [x] Type Check wird als Teil der Build-Pipeline durchgeführt. Künftige Fehler werden schon im PR abgefangen.
- [ ] Sollte etwas Kniffliges dabei sein, die ggf. länger dauern - ein neues Ticket anlegen.

### Methode

Umsetzung kann analog Components erfolgen. Hier haben wir `tsc` als Teil des `lint`-Scripts integriert:
```
"lint": "tsc --noemit && eslint src",
```

`tsc --noemit` kann auch direkt ausgeführt werden, um bestehende Problem zu finden:

<img width="1506" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/0843d59c-4e4b-4640-b2a3-f36071c9060a">

Aktueller Stand:

```
Found 49 errors in 17 files.

Errors  Files
     1  ../node_modules/@public-ui/components/src/components/toaster/toaster.tsx:45
     1  components/alert/routes.ts:8
     1  components/card/routes.ts:6
     1  components/combobox/partials/cases.tsx:27
     1  components/FocusInput.tsx:22
    10  components/handout/basic.tsx:2
     3  components/skip-nav/basic.tsx:22
     3  components/table/badge-size.tsx:29
     5  components/table/column-alignment.tsx:39
     1  components/table/render-cell.tsx:72
     2  components/table/sort-data.tsx:25
     8  components/table/stateful-with-selection.tsx:17
     7  components/table/stateless-with-selection.tsx:15
     1  components/tabs/basic.tsx:12
     1  components/tabs/icons-only.tsx:35
     1  components/types.tsx:1
     2  scenarios/inputs-get-value.tsx:58
```
