### ISSUE TITLE
Todo: Neue Focus-Methode für fokussierbare Komponenten

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6564]
Ist-Zustand: Diverse Komponenten definieren eine `focus`-Methode über den `propagateFocus`-Helper, um ein Fokussieren der Komponente von außen zu erlauben:

<img width="671" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/ae0cdb67-2aa2-4c90-841f-7f62ba84dfde">

Diese Methode hat zwei Probleme:

1) Die Komponente muss fertig initialisiert sein, bevor ein `.focus()`-Aufruf erfolgen kann. Zurzeit wird diese z.B. mit `setTimeout` umgesetzt, was zu möglichen Race-Conditions führt.
2) `focus` ist ein reservierter Name im DOM, der nicht für eigene Methoden verwendet werden sollte.

### Akzeptanzkriterien

- [x] Alle fokussierbaren Komponenten definieren eine mit `@Method()` annotierte Methode, die ein asynchrones Fokussieren erlaubt. Name der Methode: `kolFocus`
- [x] Bestehende `propagateFocus`-Nutzungen werden ebenfalls zu Methoden umgeschrieben und mit Verweis auf `kolFocus` als deprecated markiert. In `v3` können diese entfernt werden.
- [x] Verwendungen in unseren Beispiel-Apps sowie mögliche interne Verwendungen werden auf `kolFocus` umgeschrieben.
